name: Describe infrastructure events

inputs:
  repository:
    description: GitHub repository name
    required: true
  environment:
    description: Environment
    required: true
  stack:
    description: CloudFormation stack name (e.g. service)
    required: true

runs:
  using: composite
  steps:
    - name: Describe infrastructure events
      shell: bash
      run: |
        aws cloudformation describe-stack-events --stack-name ${{ format('{0}-{1}-{2}', inputs.repository, inputs.environment, inputs.stack) }}
