name: Deploy infrastructure

inputs:
  repository:
    description: GitHub repository name
    required: true
  environment:
    description: Environment
    required: true
  stack:
    description: CloudFormation stack name (e.g. service)
    required: true
  parameters:
    description: CloudFormation parameters divided by whitespace, Environment parameter should not be specified (e.g. ImageTag=123 CustomParameter=value)
    required: false
    default: ""
  aws-region:
    description: AWS region
    type: string
    required: true

runs:
  using: composite
  steps:
    - name: Package infrastructure
      shell: bash
      run: |
        aws cloudformation package \
          --template-file ./infrastructure/${{ inputs.stack }}.yml \
          --s3-bucket connery-cloud-formation-artifacts-${{ inputs.aws-region }} \
          --s3-prefix ${{ inputs.repository }} \
          --output-template-file ./infrastructure/compiled.yml

    - name: Deploy infrastructure
      shell: bash
      run: |
        aws cloudformation deploy \
          --template-file ./infrastructure/compiled.yml \
          --stack-name ${{ format('{0}-{1}-{2}', inputs.repository, inputs.environment, inputs.stack) }} \
          --s3-bucket connery-cloud-formation-artifacts-${{ inputs.aws-region }} \
          --s3-prefix ${{ inputs.repository }} \
          --parameter-overrides Environment=${{ inputs.environment }} ${{ inputs.parameters }} \
          --capabilities CAPABILITY_IAM
