name: Cancel infrastructure update

inputs:
  repository:
    description: GitHub repository name
    required: true
  environment:
    description: Environment
    required: true
  organization:
    description: Organization
    required: false
  stack:
    description: CloudFormation stack name (e.g. service)
    required: true

runs:
  using: composite
  steps:
    - name: Cancel infrastructure update
      shell: bash
      run: |
        if [[ "${{ inputs.organization }}" ]]
        then
          aws cloudformation cancel-update-stack --stack-name ${{ format('{0}-{1}-{2}-{3}', inputs.repository, inputs.environment, inputs.organization, inputs.stack) }}
          aws cloudformation wait stack-rollback-complete --stack-name ${{ format('{0}-{1}-{2}-{3}', inputs.repository, inputs.environment, inputs.organization, inputs.stack) }}
        else
          aws cloudformation cancel-update-stack --stack-name ${{ format('{0}-{1}-{2}', inputs.repository, inputs.environment, inputs.stack) }}
          aws cloudformation wait stack-rollback-complete --stack-name ${{ format('{0}-{1}-{2}', inputs.repository, inputs.environment, inputs.stack) }}
        fi
