name: Build image

on:
  workflow_call:
    inputs:
      service:
        description: Short service name
        type: string
        required: true
      docker-path:
        description: Docker path
        type: string
        required: false
        default: .

jobs:
  build-worker:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get current commit hash
        id: get-current-commit-hash
        uses: viovendi/shared-github-actions/get-current-commit-hash@master

      - name: Get current branch name
        id: get-current-branch-name
        uses: viovendi/shared-github-actions/get-current-branch-name@master

      - name: Build image
        shell: bash
        env:
          COMMIT_HASH_TAG: ${{ steps.login-ecr.outputs.registry }}/connery/${{ inputs.service }}:${{ steps.get-current-commit-hash.outputs.commit-hash }}
          BRANCH_NAME_TAG: ${{ steps.login-ecr.outputs.registry }}/connery/${{ inputs.service }}:${{ steps.get-current-branch-name.outputs.branch-name }}
        run: |
          docker pull $BRANCH_NAME_TAG || true
          docker build \
            -t $COMMIT_HASH_TAG \
            -t $BRANCH_NAME_TAG \
            --cache-from $BRANCH_NAME_TAG \
            ${{ inputs.docker-path }}
          docker push $COMMIT_HASH_TAG
          docker push $BRANCH_NAME_TAG
