name: Deploy service infrastructure

on:
  workflow_call:
    inputs:
      repository:
        description: GitHub repository name
        type: string
        required: true
      environment:
        description: Environment
        type: string
        required: true
      aws-region:
        description: AWS region
        type: string
        required: false
        default: eu-central-1

jobs:
  deploy-service-infrastructure:
    name: Deploy service infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get current commit hash
        id: get-current-commit-hash
        uses: connery-io/shared-github-actions/get-current-commit-hash@main

      - name: Check if the image exists
        shell: bash
        run: |
          aws ecr describe-images \
            --repository-name connery/${{ inputs.repository }} \
            --image-ids imageTag=${{ steps.get-current-commit-hash.outputs.commit-hash }}

      - name: Deploy infrastructure
        timeout-minutes: 15
        uses: connery-io/shared-github-actions/deploy-infrastructure@main
        with:
          repository: ${{ inputs.repository }}
          environment: ${{ inputs.environment }}
          stack: service
          parameters: ImageTag=${{ steps.get-current-commit-hash.outputs.commit-hash }}
          aws-region: ${{ inputs.aws-region }}

      - name: Describe infrastructure events
        if: failure()
        uses: connery-io/shared-github-actions/describe-infrastructure-events@main
        with:
          repository: ${{ inputs.repository }}
          environment: ${{ inputs.environment }}
          stack: service

      - name: Cancel infrastructure update
        if: cancelled()
        uses: connery-io/shared-github-actions/cancel-infrastructure-update@main
        with:
          repository: ${{ inputs.repository }}
          environment: ${{ inputs.environment }}
          stack: service
