name: Deploy service infrastructure

on:
  workflow_call:
    inputs:
      service:
        description: Short service name
        type: string
        required: true
      environment:
        description: Environment
        type: string
        required: true
      cf-stack-name-suffix:
        description: CloudFormation stack name suffix with trailing '-' (e.g. -database)
        type: string
        required: false
        default: ""
      aws-region:
        description: AWS region
        type: string
        required: false
        default: eu-central-1

jobs:
  deploy-service-infrastructure:
    name: Deploy service infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get current commit hash
        id: get-current-commit-hash
        uses: connery-io/shared-github-actions/get-current-commit-hash@main

      - name: Check if the image exists
        shell: bash
        run: |
          aws ecr describe-images \
            --repository-name connery/${{ inputs.service }} \
            --image-ids imageTag=${{ steps.get-current-commit-hash.outputs.commit-hash }}

      - name: Deploy infrastructure
        timeout-minutes: 15
        uses: connery-io/shared-github-actions/deploy-infrastructure@main
        with:
          service: ${{ inputs.service }}
          environment: ${{ inputs.environment }}
          cf-stack-name-suffix: ${{ inputs.cf-stack-name-suffix }}
          cf-template-path: ./infrastructure/service.yml
          cf-parameters: ImageTag=${{ steps.get-current-commit-hash.outputs.commit-hash }}
          aws-region: ${{ inputs.aws-region }}

      - name: Describe infrastructure events
        if: failure()
        uses: connery-io/shared-github-actions/describe-infrastructure-events@main
        with:
          service: ${{ inputs.service }}
          environment: ${{ inputs.environment }}
          cf-stack-name-suffix: ${{ inputs.cf-stack-name-suffix }}

      - name: Cancel infrastructure update
        if: cancelled()
        uses: connery-io/shared-github-actions/cancel-infrastructure-update@main
        with:
          service: ${{ inputs.service }}
          environment: ${{ inputs.environment }}
          cf-stack-name-suffix: ${{ inputs.cf-stack-name-suffix }}
