name: Remove infrastructure

on:
  workflow_call:
    inputs:
      repository:
        description: GitHub repository name
        type: string
        required: true
      environment:
        description: Environment
        type: string
        required: true
      organization:
        description: Organization
        type: string
        required: false
      stack:
        description: CloudFormation stack name (e.g. service)
        type: string
        required: true
      aws-region:
        description: AWS region
        type: string
        required: false
        default: eu-central-1

jobs:
  remove-infrastructure:
    name: Remove infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}

      - name: Remove infrastructure
        timeout-minutes: 15
        shell: bash
        run: |
          if [[ "${{ inputs.organization }}" ]]
          then
            aws cloudformation delete-stack --stack-name ${{ format('{0}-{1}-{2}-{3}', inputs.repository, inputs.environment, inputs.organization, inputs.stack) }}
            aws cloudformation wait stack-delete-complete --stack-name ${{ format('{0}-{1}-{2}-{3}', inputs.repository, inputs.environment, inputs.organization, inputs.stack) }}
          else
            aws cloudformation delete-stack --stack-name ${{ format('{0}-{1}-{2}', inputs.repository, inputs.environment, inputs.stack) }}
            aws cloudformation wait stack-delete-complete --stack-name ${{ format('{0}-{1}-{2}', inputs.repository, inputs.environment, inputs.stack) }}
          fi

      - name: Describe infrastructure events
        if: failure()
        uses: connery-io/shared-github-actions/describe-infrastructure-events@main
        with:
          repository: ${{ inputs.repository }}
          environment: ${{ inputs.environment }}
          organization: ${{ inputs.organization }}
          stack: ${{ inputs.stack }}
